### ISSUE TITLE
Duplicate code issue

### ISSUE THREAD

**Issue by chandrakant38370** [TestOrginazation1/NewRepoForOrg#2]
** Coconut Wallpapers**

[About forest.txt](https://github.com/TestOrginazation1/NewRepoForOrg/files/6904937/About.forest.txt)

**Comment by jainshri** [comment]
test
[Connector Checklist.xlsx](https://github.com/TestOrginazation1/NewRepoForOrg/files/6944553/Connector.Checklist.xlsx)

**Comment by chandrakant38370** [comment]
Issue is Closing by me
